---
- name: Disable and stop recording on both cameras
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
 
    - name: Disable and stop camera0 service
      service:
        name: camera0
        state: stopped
        enabled: false
        
    - name: Disable and stop camera1 service
      service:
        name: camera1
        state: stopped
        enabled: false
        
    - name: Disable and stop sensors service
      service:
        name: sensors
        state: stopped
        enabled: false
