---
- name: Purge old data
  hosts: localhost
  gather_facts: no
  become: true
  tasks:
    - name: Find camera0 data files
      find:
        paths: /home/pi/camera0
        patterns: (?i).rec*.h264
        use_regex: true
      register: rm_camera0
    
    - name: Find camera1 data files
      find:
        paths: /home/pi/camera1
        patterns: (?i).rec*.h264
        use_regex: true
      register: rm_camera1
            
    - name: Find IIS data files
      find:
        paths: /home/pi/sensors
        patterns: (?i).IIS_*.bin
        use_regex: true
      register: rm_iis
    
    - name: Remove camera0 data files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ rm_camera0.files }}"
      loop_control:
        label: "{{ item.path }}"
        
    - name: Remove camera1 data files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ rm_camera1.files }}"
      loop_control:
        label: "{{ item.path }}"
        
    - name: Remove IIS data files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ rm_iis.files }}"
      loop_control:
        label: "{{ item.path }}"
