---
- name: Setup Kreweta CM4
  hosts: localhost
  become: true
  tasks:
  
    - name: Remove /etc/profile.d/sshpwd.sh
      ansible.builtin.file:
        path: "/etc/profile.d/sshpwd.sh"
        state: "absent"
        
    - name: Remove motd
      ansible.builtin.file:
        path: "/etc/motd"
        state: "absent"
      
    # - name: Fetch sq3tle public key
    #   uri:
    #     url: "https://github.com/sq3tle.keys"
    #     return_content: yes
    #   register: key_sq3tle

    # - name: Append sq3tle to authorized_keys
    #   lineinfile:
    #     dest: "~/.ssh/authorized_keys"
    #     line: "{{ key_sq3tle.content }}"
    #     create: True
      
    # - name: Fetch Duszkiewicz public key
    #   uri:
    #     url: "https://github.com/Duszkiewicz.keys"
    #     return_content: yes
    #   register: key_Duszkiewicz

    # - name: Append Duszkiewicz key to authorized_keys
    #   lineinfile:
    #     dest: "~/.ssh/authorized_keys"
    #     line: "{{ key_Duszkiewicz.content }}"

    - name: Enable Camera_0 
      lineinfile:
          path: /boot/config.txt
          line: "dtoverlay=ov5647,cam0"
          
    - name: Enable Camera_1
      lineinfile:
          path: /boot/config.txt
          line: "dtoverlay=ov5647,cam1"

    - name: Enable SPI
      lineinfile:
          path: /boot/config.txt
          line: "dtparam=spi=on"
    
    - name: Enable I2C_1
      lineinfile:
          path: /boot/config.txt
          line: "dtparam=i2c1=on"

    - name: Enable I2C_10
      lineinfile:
          path: /boot/config.txt
          line: "dtparam=i2c_arm=on"
          
    - name: Enable hardware PWM on GPIO12 (Grove near USB)
      lineinfile:
          path: /boot/config.txt
          line: "dtoverlay=pwm,pin=12,func=4"

    - name: Enable RTC (WIP!!!)
      lineinfile:
          path: /boot/config.txt
          line: "dtoverlay=i2c-rtc,rv3028,backup-switchover-mode=1,i2c_csi_dsi"
    
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - i2c-tools
        - git
        - python3
        - python3-pip
        
    - name: Create service for camera0
      copy:
        content: |
          [Unit]
          Description=Camera_0 recording service

          [Service]
          Restart=on-failure
          RestartSec=5s
          WorkingDirectory=/home/pi/data
          ExecStart=/bin/libcamera-vid --split --segment 10000 -o /home/pi/camera0/cam_%%06d.h264 --inline -t 0 -v 0 --width 1920 --height 1080 --camera 0 --framerate 10 -b 4000000

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/camera0.service
        
    - name: Create service for camera1
      copy:
        content: |
          [Unit]
          Description=Camera_1 recording service

          [Service]
          Restart=on-failure
          RestartSec=5s
          WorkingDirectory=/home/pi/data
          ExecStart=/bin/libcamera-vid --split --segment 10000 -o /home/pi/camera1/cam_%%06d.h264 --inline -t 0 -v 0 --width 1920 --height 1080 --camera 1 --framerate 10 -b 4000000

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/camera1.service
        
    - name: Creates directory for camera0 recordings
      file:
        path: /home/pi/camera0
        state: directory    
        
    - name: Creates directory for camera1 recordings
      file:
        path: /home/pi/camera1
        state: directory    
        
#     - name: Creates directory for sensor data
#       file:
#         path: /home/pi/sensors
#         state: directory   
        
    - name: Reload systemd
      systemd:
        daemon_reload: yes
    
    - name: Copy sensors folders
      copy: remote_src=True src=/home/pi/setup/sensors dest=/home/pi
    
    - name: Compile iis_recoderder
      command: /bin/gcc -o /home/pi/sensors/iis_recorder /home/pi/sensors/iis_recorder.c /home/pi/sensors/iis3dwb_reg.c -lm
      
    - name: Create service for sensors
      copy:
        content: |
          [Unit]
          Description=Sensors recording service

          [Service]
          Restart=on-failure
          RestartSec=5s
          WorkingDirectory=/home/pi/sensors
          ExecStart=/home/pi/sensors/iis_recoder

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/camera1.service
    
       
